export default [
    {
        id: 1,
        postedOn: "2024-12-5",
        title: "iOS Developer",
        company: "Apple",
        type: "Tempo Integral",
        experience: "Nível Intermerdiário",
        location: "Remoto",
        skills: ["SwiftUI", "UiKit", "Core Data"],
        job_link: "https://www.apple.com/careers/br/",
    },
    {
        id: 2,
        postedOn: "2024-12-10",
        title: "Front-end Developer",
        company: "Amazon",
        type: "Tempo Integral",
        experience: "Sem Experiência",
        location: "Presencial", 
        skills: ["JavaScript", "nextjs", "Tailwind CSS"],
        job_link: "https://www.amazon.jobs/br/",
    },
    {
        id: 3,
        postedOn: "2024-12-12",
        title: "Back-end Developer",
        company: "Google",
        type: "Tempo Parcial",
        experience: "Nível Senior",
        location: "Híbrido",
        skills: ["Kotlin", "MongoDB", "Docker"],
        job_link: "https://careers.google.com/jobs/",
    },
    {
        id: 4,
        postedOn: "2024-12-13",
        title: "Android Developer",
        company: "Facebook",
        type: "Contrato PJ",
        experience: "Nível Junior",
        location: "Remoto",
        skills: ["Kotlin", "Java", "Android Studio"],
        job_link: "https://www.facebook.com/careers/",
    },
    {
        id: 5,
        postedOn: "2024-12-18",
        title: "Developer Advocate",
        company: "Twitter",
        type: "Tempo Integral",
        experience: "Sem Experiência",
        location: "Presencial",
        skills: ["JavaScript", "React", "Nodejs"],
        job_link: "https://careers.twitter.com/en.html",
    },
    {
        id: 6,
        postedOn: "2024-12-22",
        title: "Developer Jr.",
        company: "Twitter",
        type: "Híbrido",
        experience: "Sem Experiência",
        location: "Presencial",
        skills: ["JavaScript", "React", "Nodejs"],
        job_link: "https://careers.twitter.com/en.html",
    },
];